### ISSUE TITLE
Allow multiple broadcast addresses

### ISSUE THREAD

**Issue by marcelrv** [tkurki/udp-nmea-plugin#12]
It's there a way to setup the plugin to have multiple broadcast adresses,
E.g. my setup has 2 network subnets 10.10.10.0 & 192.168.8.0 would like it to send up on both

**Comment by tkurki** [comment]
I rewrote the plugin to support multiple destinations. Can you try it out? you can install the dev version by running `npm install https://github.com/tkurki/udp-nmea-plugin#multiple-destinations` in $HOME/.signalk AND eventually you'll need to edit package.json there so that when this is published in npm you'll get the proper version.

**Comment by marcelrv** [comment]
You are amazing fast, great thanks!
Works like a charm!
